# Generated by Django 2.2.7 on 2019-11-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
