# Generated by Django 2.2.7 on 2019-11-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
