# Generated by Django 2.2.7 on 2019-11-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='default-slug', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='photo_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
