# Generated by Django 2.2.7 on 2019-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arc_app', '0002_auto_20191108_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
